import fs from 'fs-extra';
import path from 'path';
import os from 'os';
import { execSync } from 'child_process';

const TMP_DIR = path.join(os.tmpdir(), 'figma-to-react');
const BACKUP_DIR = path.join(os.tmpdir(), 'figma-to-react-test-backup');

/**
 * Gets the temp directory path
 */
export function getTmpDir(): string {
  return TMP_DIR;
}

/**
 * Backs up the existing figma-to-react temp directory
 */
export async function backupTmpDir(): Promise<void> {
  if (await fs.pathExists(TMP_DIR)) {
    await fs.move(TMP_DIR, BACKUP_DIR, { overwrite: true });
  }
}

/**
 * Restores the backed up figma-to-react temp directory
 */
export async function restoreTmpDir(): Promise<void> {
  if (await fs.pathExists(BACKUP_DIR)) {
    await fs.remove(TMP_DIR);
    await fs.move(BACKUP_DIR, TMP_DIR);
  }
}

/**
 * Cleans the figma-to-react temp directory
 */
export async function cleanTmpDir(): Promise<void> {
  await fs.remove(TMP_DIR);
}

/**
 * Resets the test project to its clean state
 */
export async function resetTestProject(testProjectPath: string): Promise<void> {
  // Remove generated directories
  const dirsToRemove = [
    'src/components',
    'src/styles',
    'src/pages',
    'public/figma-assets',
  ];

  for (const dir of dirsToRemove) {
    const fullPath = path.join(testProjectPath, dir);
    if (await fs.pathExists(fullPath)) {
      await fs.remove(fullPath);
    }
  }

  // Reset index.css to template
  const templatePath = path.join(testProjectPath, 'src/index.css.template');
  const cssPath = path.join(testProjectPath, 'src/index.css');

  if (await fs.pathExists(templatePath)) {
    await fs.copy(templatePath, cssPath, { overwrite: true });
  }

  // Reset App.tsx to original
  const appPath = path.join(testProjectPath, 'src/App.tsx');
  const appContent = `import { useSearchParams } from 'react-router-dom';

function App() {
  const [searchParams] = useSearchParams();
  const screen = searchParams.get('screen');

  if (screen) {
    // Dynamic component loading for figma-preview route
    // Components will be generated by the skill and placed in src/components/
    return (
      <div data-figma-component={screen}>
        <p>Component "{screen}" not found. Run the figma-to-react skill first.</p>
      </div>
    );
  }

  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold">Figma to React Test Project</h1>
      <p className="mt-4 text-gray-600">
        This project is used for E2E testing of the figma-to-react skill.
      </p>
    </div>
  );
}

export default App;
`;
  await fs.writeFile(appPath, appContent);
}

/**
 * Kills any lingering dev server processes
 */
export async function killDevServers(): Promise<void> {
  try {
    execSync('pkill -f "vite.*test-project"', { stdio: 'ignore' });
  } catch {
    // Ignore errors - no processes to kill
  }
}

/**
 * Installs dependencies for the test project if needed
 */
export async function installTestProjectDeps(testProjectPath: string): Promise<void> {
  const nodeModulesPath = path.join(testProjectPath, 'node_modules');

  if (!(await fs.pathExists(nodeModulesPath))) {
    console.log('Installing test project dependencies...');
    execSync('pnpm install', { cwd: testProjectPath, stdio: 'inherit' });
  }
}

/**
 * Installs Playwright browser if needed
 */
export async function installPlaywright(testProjectPath: string): Promise<void> {
  try {
    execSync('npx playwright --version', { cwd: testProjectPath, stdio: 'ignore' });
  } catch {
    console.log('Installing Playwright chromium...');
    execSync('npx playwright install chromium', { cwd: testProjectPath, stdio: 'inherit' });
  }
}

/**
 * Checks if ImageMagick is available
 */
export function isImageMagickAvailable(): boolean {
  try {
    execSync('magick --version', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}
