import { useSearchParams } from 'react-router-dom';

function App() {
  const [searchParams] = useSearchParams();
  const screen = searchParams.get('screen');

  if (screen) {
    // Dynamic component loading for figma-preview route
    // Components will be generated by the skill and placed in src/components/
    return (
      <div data-figma-component={screen}>
        <p>Component "{screen}" not found. Run the figma-to-react skill first.</p>
      </div>
    );
  }

  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold">Figma to React Test Project</h1>
      <p className="mt-4 text-gray-600">
        This project is used for E2E testing of the figma-to-react skill.
      </p>
    </div>
  );
}

export default App;
